EASY_GAME_CODE = "EASY"
HARD_GAME_CODE = "HARD"
CHALLENGING_GAME_CODE = "CHALLENGING"
EMPTY_ANSWERS_LIST_CODE = -1
VALID_SONGS_ANSWERS_LIST_SIZE = 4
CRASHING_MODE = "CRASH"
WORKING_MODE = "WORKING_SERVER"
